apiVersion: v1
kind: Pod
metadata:
  name: secretbox2
spec:
  containers:
  - name: secretbox
    image: busybox
    command:
    - sleep
    - "3600"
    volumeMounts:
    - name: secret
      mountPath: /secretstuff
  volumes:
  - name: secret
    secret:
      secretName: secretstuff
