apiVersion: v1
kind: Pod
metadata:
  name: mymysql
spec:
  containers:
  - name: famke-mysql 
    image: busybox
    command:
    - sleep
    - "3600"
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql
          key: password
